// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVzWrMBX4Dx_O107y2Dzm_L0MdUWhh9j8',
    appId: '1:374870354810:web:44cce83759772099bb04c3',
    messagingSenderId: '374870354810',
    projectId: 'e-commerce-project-46caf',
    authDomain: 'e-commerce-project-46caf.firebaseapp.com',
    storageBucket: 'e-commerce-project-46caf.firebasestorage.app',
    measurementId: 'G-FSM8H5RTQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQGbrAnfjD7iugo9Nynq-V-IemBzak-U',
    appId: '1:374870354810:android:97243b16075d5d4abb04c3',
    messagingSenderId: '374870354810',
    projectId: 'e-commerce-project-46caf',
    storageBucket: 'e-commerce-project-46caf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASUP-lMBrFuarKgPpnPB924SecOqB9qOc',
    appId: '1:374870354810:ios:8728423066287f10bb04c3',
    messagingSenderId: '374870354810',
    projectId: 'e-commerce-project-46caf',
    storageBucket: 'e-commerce-project-46caf.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASUP-lMBrFuarKgPpnPB924SecOqB9qOc',
    appId: '1:374870354810:ios:8728423066287f10bb04c3',
    messagingSenderId: '374870354810',
    projectId: 'e-commerce-project-46caf',
    storageBucket: 'e-commerce-project-46caf.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVzWrMBX4Dx_O107y2Dzm_L0MdUWhh9j8',
    appId: '1:374870354810:web:784d7f8cc5b34d35bb04c3',
    messagingSenderId: '374870354810',
    projectId: 'e-commerce-project-46caf',
    authDomain: 'e-commerce-project-46caf.firebaseapp.com',
    storageBucket: 'e-commerce-project-46caf.firebasestorage.app',
    measurementId: 'G-WS1K5SMESS',
  );
}
